### PR TITLE
fix: ndirect modification of overloaded

### PR DESCRIPTION
**Pull request by dominikzogg**

### CODE REVIEW

**Comment by dominikzogg** [comment]
#65

**Comment by JarJak** [comment]
+1

**Comment by GromNaN** [comment]
:+1:

**Comment by dominikzogg** [comment]
@fabpot any news on this? seems to be the only needed fix for sf2.7 compability

**Comment by GawainLynch** [comment]
…and greatly desired by a few people. We're still having to work-around it.

**Comment by Hadrien45** [comment]
:+1:

**Comment by bobdenotter** [comment]
:+1: Would love to have this.

**Comment by fabpot** [comment]
Thank you @dominikzogg.

**Comment by fabpot** [comment]
1.0.7 is out.

**Comment by dominikzogg** [comment]
thank you too
Am 04.06.2015 4:28 nachm. schrieb "Fabien Potencier" <
notifications@github.com>:

**Pull request merged**
