### PR TITLE
Allow symfony 3.1

### PR DESCRIPTION
**Pull request by mvanbaak**
As I was updating my skeleton app, I found out the webprofiler did not support symfony 3.1 in composer.json.
So I tried to update it.

Everything works great, except for the web-profiler-bundle.
This PR broke it: https://github.com/symfony/symfony/pull/17589

I don't know the best way to fix that. Maybe you have an idea? (I'm not that familiar with the silex and symfony development)

### CODE REVIEW

**Comment by mvanbaak** [comment]
I updated the web-profile-bundle as well now symfony 3.1.1 is out.
This is ready to go.

**Comment by fabpot** [comment]
Do we need to mark 3.1.0 as conflicting?

**Comment by mvanbaak** [comment]
Yeah, probably best to do that since it will break.

**Comment by fabpot** [comment]
Can you update composer.json accordingly before I merge?

**Comment by mvanbaak** [comment]
done :)

**Comment by fabpot** [comment]
Thank you @mvanbaak.

**Pull request closed without merging**
